### ISSUE TITLE
RSI: 0.0000000 and MFI: 0.0000000 trigger false notifications

### ISSUE THREAD

**Issue by opoloko** [CryptoSignal/crypto-signal#370]
Hi

as this is a Docker and so quite inconvenient to modify, could you please fix the problem (already flagged) of signals values 0.00000000 triggering alerts??

Should be easy enough to in notification.py to make notification false if the value is 0.00000000 because that means obviously that the analysis or data were not enough or valid.

Could you please fix it so we can pull the updated Docker image?

**Comment by laliux** [comment]
Hey @opoloko 

That is fixed, but still in develop branch. Check the REAME there:

https://github.com/CryptoSignal/crypto-signal/blob/develop/README.md

Best

**Comment by opoloko** [comment]
Hi thanks, I tried the devel but I still get same problem on MFI indicator: trigger HOT when value is 0.00

[5m / 14] binance-ALGO/BTC-mfi-0 is hot! ({'mfi': '0.00'})

**Comment by opoloko** [comment]
Hi

the crossovers as well triggered for opening/closing value of 0.00...it seems generally speaking nothing should be triggered for a 0.00 (I can't think of any indicator going down to 0.00000000 while instead that is more a sign of data not arrived).

Is the dev version fixed also for other indicators? Getting lots of false positives because of that :-)
